# Generated by Django 5.1.4 on 2025-04-28 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='network_flows',
            field=models.ManyToManyField(blank=True, related_name='agents', to='api.networkflow'),
        ),
        migrations.AddField(
            model_name='attacktype',
            name='alerts',
            field=models.ManyToManyField(blank=True, related_name='attack_types', to='api.alert'),
        ),
        migrations.AddField(
            model_name='attacktype',
            name='threats',
            field=models.ManyToManyField(blank=True, related_name='attack_types', to='api.threat'),
        ),
    ]
