# Generated by Django 5.1.4 on 2025-05-01 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_agent_network_flows_attacktype_alerts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('can_view_dashboard', models.BooleanField(default=False)),
                ('can_view_reports', models.BooleanField(default=False)),
                ('can_edit_reports', models.BooleanField(default=False)),
                ('can_delete_reports', models.BooleanField(default=False)),
                ('can_view_users', models.BooleanField(default=False)),
                ('can_edit_users', models.BooleanField(default=False)),
                ('can_delete_users', models.BooleanField(default=False)),
                ('can_view_notifications', models.BooleanField(default=False)),
                ('can_manage_notifications', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Permission Group',
                'verbose_name_plural': 'Permission Groups',
            },
        ),
    ]
