# Generated by Django 5.1.5 on 2025-02-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_notification_alert_alter_notification_threat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='notifications',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notifications',
            field=models.ManyToManyField(blank=True, related_name='user_notifications', to='accounts.notification'),
        ),
    ]
