# Generated by Django 5.1.5 on 2025-02-07 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_userprofile_notifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='attack_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='accounts.attacktype'),
        ),
        migrations.AddField(
            model_name='networkflow',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='network_flows', to='accounts.agent'),
        ),
        migrations.AddField(
            model_name='suspiciousip',
            name='alert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspicious_ips', to='accounts.alert'),
        ),
        migrations.AddField(
            model_name='suspiciousip',
            name='threat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspicious_ips', to='accounts.threat'),
        ),
        migrations.AddField(
            model_name='threat',
            name='attack_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threats', to='accounts.attacktype'),
        ),
    ]
