# Generated by Django 5.1.4 on 2025-04-28 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttackType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='System_Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(default='Osiris Network Analysis System', max_length=100)),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('max_login_attempts', models.IntegerField(default=5)),
                ('notification_settings', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_agents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_id', models.CharField(max_length=255, unique=True)),
                ('src_ip', models.GenericIPAddressField()),
                ('src_port', models.IntegerField()),
                ('dst_ip', models.GenericIPAddressField()),
                ('dst_port', models.IntegerField()),
                ('protocol', models.CharField(max_length=10)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('packet_count', models.IntegerField()),
                ('total_bytes', models.BigIntegerField()),
                ('duration', models.FloatField(blank=True, null=True)),
                ('avg_packet_size', models.FloatField(blank=True, null=True)),
                ('std_packet_size', models.FloatField(blank=True, null=True)),
                ('min_packet_size', models.IntegerField(blank=True, null=True)),
                ('max_packet_size', models.IntegerField(blank=True, null=True)),
                ('bytes_per_second', models.FloatField(blank=True, null=True)),
                ('packets_per_second', models.FloatField(blank=True, null=True)),
                ('threat_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('threat_details', models.JSONField(default=list)),
                ('anomalies', models.JSONField(default=list)),
                ('protocol_analysis', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['src_ip', 'dst_ip'], name='api_network_src_ip_6a396e_idx'), models.Index(fields=['threat_level'], name='api_network_threat__b23f44_idx'), models.Index(fields=['created_at'], name='api_network_created_2f3168_idx')],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('false_positive', 'False Positive')], default='new', max_length=20)),
                ('description', models.TextField()),
                ('threat_type', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='api.networkflow')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Threat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('scan', 'Port Scan'), ('dos', 'Denial of Service'), ('brute_force', 'Brute Force'), ('malware', 'Malware'), ('suspicious', 'Suspicious Activity'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('confidence', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_threats', to='api.networkflow')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SuspiciousIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('date', models.DateField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspicious_ips', to='api.alert')),
                ('threat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspicious_ips', to='api.threat')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report_status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('review', 'In Review')], max_length=20)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_alert_reports', to='api.alert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_reports', to=settings.AUTH_USER_MODEL)),
                ('threat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_threat_reports', to='api.threat')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('notification_type', models.CharField(blank=True, choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification')], max_length=20, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_alert_notifications', to='api.alert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_notifications', to=settings.AUTH_USER_MODEL)),
                ('threat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_threat_notifications', to='api.threat')),
            ],
        ),
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_userlogins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['severity'], name='api_alert_severit_40581a_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['status'], name='api_alert_status_d0d329_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['created_at'], name='api_alert_created_b16782_idx'),
        ),
        migrations.AddIndex(
            model_name='threat',
            index=models.Index(fields=['category'], name='api_threat_categor_f72829_idx'),
        ),
        migrations.AddIndex(
            model_name='threat',
            index=models.Index(fields=['confidence'], name='api_threat_confide_3d55e2_idx'),
        ),
        migrations.AddIndex(
            model_name='threat',
            index=models.Index(fields=['created_at'], name='api_threat_created_47dac7_idx'),
        ),
    ]
