# Generated by Django 5.1.4 on 2025-06-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_notification_options_notification_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='threat',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='high', max_length=20),
        ),
        migrations.AddField(
            model_name='threat',
            name='source_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='threat',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('investigating', 'Investigating'), ('false_positive', 'False Positive')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='threat',
            name='target_device',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='threat',
            name='threat_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='threat',
            index=models.Index(fields=['status'], name='api_threat_status_945b35_idx'),
        ),
        migrations.AddIndex(
            model_name='threat',
            index=models.Index(fields=['severity'], name='api_threat_severit_6a3635_idx'),
        ),
    ]
