# Generated by Django 5.1.5 on 2025-02-04 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_notification_user_alter_report_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='alert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts_alert_notifications', to='accounts.alert'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='threat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts_threat_notifications', to='accounts.threat'),
        ),
        migrations.AlterField(
            model_name='report',
            name='alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts_alert_reports', to='accounts.alert'),
        ),
        migrations.AlterField(
            model_name='report',
            name='threat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts_threat_reports', to='accounts.threat'),
        ),
    ]
