# Generated by Django 5.1.5 on 2025-04-22 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_userprofile_bio_userprofile_is_email_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('can_view_dashboard', models.BooleanField(default=False)),
                ('can_view_users', models.BooleanField(default=False)),
                ('can_add_users', models.BooleanField(default=False)),
                ('can_edit_users', models.BooleanField(default=False)),
                ('can_delete_users', models.BooleanField(default=False)),
                ('can_view_reports', models.BooleanField(default=False)),
                ('can_add_reports', models.BooleanField(default=False)),
                ('can_edit_reports', models.BooleanField(default=False)),
                ('can_delete_reports', models.BooleanField(default=False)),
                ('can_view_threats', models.BooleanField(default=False)),
                ('can_add_threats', models.BooleanField(default=False)),
                ('can_edit_threats', models.BooleanField(default=False)),
                ('can_delete_threats', models.BooleanField(default=False)),
                ('can_view_notifications', models.BooleanField(default=False)),
                ('can_manage_notifications', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='permission_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.permissiongroup'),
        ),
    ]
