# Generated by Django 5.1.4 on 2025-05-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_agent_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notify_on_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_on_reports',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_on_threats',
            field=models.BooleanField(default=True),
        ),
    ]
